# Generated by Django 5.0.6 on 2024-11-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0003_remove_medico_medico_colegiatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='medico_nrodocumento',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
