# Generated by Django 5.0.6 on 2024-11-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminlite', '0003_profile_old_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='old_picture',
        ),
    ]
