# Generated by Django 5.0.6 on 2024-11-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paciente_edadtipo',
            field=models.CharField(blank=True, choices=[('años', 'Años'), ('meses', 'Meses')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paciente_sexo',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=12, null=True),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('paciente_dni',), name='unique_dni'),
        ),
    ]
