# Generated by Django 5.0.6 on 2024-11-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_remove_paciente_paciente_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='paciente_celular',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
