# Generated by Django 5.0.6 on 2024-11-13 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_rename_email_proveedores_email_prov'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
