# Generated by Django 5.0.6 on 2024-11-19 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_options_remove_paciente_unique_dni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='paciente_edad',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='paciente_edadtipo',
        ),
    ]
