# Generated by Django 5.0.6 on 2024-11-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_alter_paciente_paciente_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='paciente_celular',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paciente_dni',
            field=models.CharField(blank=True, max_length=35, null=True, unique=True),
        ),
    ]
