# Generated by Django 5.0.6 on 2024-11-05 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analisis_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('analisis_fregistro', models.DateField(blank=True, null=True)),
                ('analisis_estatus', models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=8, null=True)),
            ],
            options={
                'db_table': 'analisis',
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examen_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('examen_fregistro', models.DateField(blank=True, null=True)),
                ('examen_estatus', models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=8, null=True)),
                ('analisis_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='examenes.analisis')),
            ],
            options={
                'db_table': 'examen',
            },
        ),
        migrations.CreateModel(
            name='RealizarExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizarexamen_estatus', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('FINALIZADO', 'Finalizado')], max_length=10, null=True)),
                ('realizarexamen_indica', models.CharField(blank=True, max_length=255, null=True)),
                ('realizarexamen_nomindica', models.CharField(blank=True, max_length=255, null=True)),
                ('realizarexamen_fregistro', models.DateField(blank=True, null=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pacientes.paciente')),
            ],
            options={
                'db_table': 'realizar_examen',
            },
        ),
        migrations.CreateModel(
            name='RealizarExamenDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analisis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='examenes.analisis')),
                ('examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='examenes.examen')),
                ('realizarexamen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='examenes.realizarexamen')),
            ],
            options={
                'db_table': 'realizar_examen_detalle',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_fregistro', models.DateField(blank=True, null=True)),
                ('resultado_estatus', models.CharField(blank=True, max_length=1, null=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pacientes.paciente')),
            ],
            options={
                'db_table': 'resultado',
            },
        ),
        migrations.CreateModel(
            name='ResultadoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resuldetalle_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('rdetalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='examenes.realizarexamendetalle')),
                ('resultado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='examenes.resultado')),
            ],
            options={
                'db_table': 'resultado_detalle',
            },
        ),
        migrations.AddIndex(
            model_name='examen',
            index=models.Index(fields=['analisis_id'], name='examen_analisi_36cbc0_idx'),
        ),
        migrations.AddIndex(
            model_name='realizarexamen',
            index=models.Index(fields=['paciente'], name='realizar_ex_pacient_d97178_idx'),
        ),
        migrations.AddIndex(
            model_name='realizarexamendetalle',
            index=models.Index(fields=['examen'], name='realizar_ex_examen__dbb9fe_idx'),
        ),
        migrations.AddIndex(
            model_name='realizarexamendetalle',
            index=models.Index(fields=['analisis'], name='realizar_ex_analisi_4e0851_idx'),
        ),
        migrations.AddIndex(
            model_name='realizarexamendetalle',
            index=models.Index(fields=['realizarexamen'], name='realizar_ex_realiza_2e0571_idx'),
        ),
        migrations.AddIndex(
            model_name='resultado',
            index=models.Index(fields=['paciente'], name='resultado_pacient_5bbb74_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadodetalle',
            index=models.Index(fields=['resultado'], name='resultado_d_resulta_f43d34_idx'),
        ),
        migrations.AddIndex(
            model_name='resultadodetalle',
            index=models.Index(fields=['rdetalle'], name='resultado_d_rdetall_63249c_idx'),
        ),
    ]
