# Generated by Django 5.0.6 on 2024-12-02 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0008_remove_resultado_resultado_pacient_5bbb74_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='resultado',
            name='resultado_pacient_895da5_idx',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='paciente_id',
        ),
        migrations.AddField(
            model_name='resultado',
            name='realizarexamen_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='examenes.realizarexamen'),
        ),
    ]
