# Generated by Django 5.0.6 on 2024-12-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0009_remove_resultado_resultado_pacient_895da5_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadodetalle',
            name='resuldetalle_archivo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
