# Generated by Django 5.0.6 on 2024-11-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('paciente_apepaterno', models.CharField(blank=True, max_length=100, null=True)),
                ('paciente_apematerno', models.CharField(blank=True, max_length=100, null=True)),
                ('paciente_dni', models.CharField(blank=True, max_length=8, null=True)),
                ('paciente_celular', models.CharField(blank=True, max_length=12, null=True)),
                ('paciente_edad', models.IntegerField(blank=True, null=True)),
                ('paciente_edadtipo', models.CharField(blank=True, max_length=10, null=True)),
                ('paciente_sexo', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
    ]
