# Generated by Django 5.0.6 on 2024-11-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['paciente_nombres'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.RemoveConstraint(
            model_name='paciente',
            name='unique_dni',
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='paciente_dni',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('paciente_dni',), name='paciente_dni'),
        ),
    ]
