# Generated by Django 5.0.6 on 2024-11-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_paciente_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='paciente_sexo',
            field=models.CharField(blank=True, choices=[('masculino', 'MASCULINO'), ('femenino', 'FEMENINO')], max_length=12, null=True),
        ),
    ]
