# Generated by Django 5.0.6 on 2024-11-06 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('especialidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('especialidad_fregistro', models.DateField(blank=True, null=True)),
                ('especialidad_estatus', models.CharField(blank=True, choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=8, null=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidad',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('medico_id', models.AutoField(primary_key=True, serialize=False)),
                ('medico_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('medico_apepat', models.CharField(blank=True, max_length=100, null=True)),
                ('medico_apemat', models.CharField(blank=True, max_length=100, null=True)),
                ('medico_direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('medico_movil', models.CharField(blank=True, max_length=100, null=True)),
                ('medico_fenac', models.DateField(blank=True, null=True)),
                ('medico_nrodocumento', models.CharField(blank=True, max_length=8, null=True)),
                ('medico_colegiatura', models.CharField(blank=True, max_length=8, null=True)),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='examenes.especialidad')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'db_table': 'medico',
            },
        ),
    ]
