# Generated by Django 5.0.6 on 2024-11-26 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_especialidad_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='medico_colegiatura',
        ),
    ]
