# Generated by Django 5.0.6 on 2024-11-27 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0004_alter_medico_medico_nrodocumento'),
        ('pacientes', '0008_alter_paciente_paciente_sexo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='realizarexamen',
            name='realizar_ex_pacient_d97178_idx',
        ),
        migrations.RenameField(
            model_name='realizarexamen',
            old_name='paciente',
            new_name='paciente_id',
        ),
        migrations.RemoveField(
            model_name='realizarexamen',
            name='realizarexamen_indica',
        ),
        migrations.AddField(
            model_name='realizarexamen',
            name='medico_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='examenes.medico'),
        ),
        migrations.AddIndex(
            model_name='realizarexamen',
            index=models.Index(fields=['paciente_id'], name='realizar_ex_pacient_a9c5d3_idx'),
        ),
    ]
