# Generated by Django 5.0.6 on 2024-11-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlite', '0002_rol_alter_profile_options_profile_usu_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='old_picture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
