# Generated by Django 5.0.6 on 2024-11-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('cedula_prov', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('rif', models.CharField(max_length=15)),
                ('nombre_prov', models.CharField(max_length=20)),
                ('apellido_prov', models.CharField(max_length=20)),
                ('direccion_prov', models.CharField(max_length=35)),
                ('telefono_prov', models.CharField(max_length=20)),
            ],
        ),
    ]
