# Generated by Django 5.0.6 on 2024-11-13 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedores_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedores',
            old_name='email',
            new_name='email_prov',
        ),
    ]
