# Generated by Django 5.0.6 on 2024-11-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(default=1, max_length=55),
            preserve_default=False,
        ),
    ]
