# Generated by Django 5.0.6 on 2024-11-26 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_productos_descripcion'),
        ('proveedores', '0004_proveedores_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='proveedores.proveedores'),
        ),
    ]
